import { client } from './client';

export const all_clients : client[] = [
    {"id":"2","username":"adminl","prefix":"ED","email":"ajay010791@gmail.com","comp_name":"edu","status":"1","is_deleted":"0"},
    {"id":"3","username":"admin123","prefix":"abc","email":"admin123@gmail.com","comp_name":"IWS","status":"1","is_deleted":"0"},{"id":"6","username":"testvdfxb","prefix":"raju","email":"kumar55@gmail.com","comp_name":"","status":"1","is_deleted":"0"},{"id":"7","username":"sdadsd","prefix":"sdasdasd","email":"sdasdasd","comp_name":"sdasd","status":"1","is_deleted":"0"},{"id":"8","username":"fsdfsd","prefix":"dfsfsdfsd","email":"hfdgdfg","comp_name":"dfsdfsdf","status":"1","is_deleted":"0"},{"id":"9","username":"kumarsharma","prefix":"pkumar","email":"rajkumar55@gmail.com","comp_name":"kumarp","status":"1","is_deleted":"0"},{"id":"10","username":"fsdfsdfsd","prefix":"dsfsdfsdf","email":"dfsfdsf","comp_name":"dfsfsdfsd","status":"1","is_deleted":"0"},{"id":"11","username":"test","prefix":"rawer","email":"test@gmail.com","comp_name":"bcaoeufhiew","status":"1","is_deleted":"0"},{"id":"12","username":"vinod","prefix":"pro","email":"v@t.com","comp_name":"prov","status":"1","is_deleted":"0"},{"id":"13","username":"Vipin Kumar","prefix":"online_sell","email":"vipin.kumar@industrybuying.com","comp_name":"industry Buying","status":"1","is_deleted":"0"},{"id":"14","username":"kumar pawan","prefix":"interior","email":"pawananimator@gmail.com","comp_name":"interiorDesign","status":"1","is_deleted":"0"},{"id":"15","username":"test1","prefix":"dsvg","email":"tets@fmail.com","comp_name":"vdfsvdf","status":"1","is_deleted":"0"},{"id":"16","username":"rajubangayagentleman","prefix":"gent","email":"raju_gentleman@gmail.com","comp_name":"GentleMan","status":"1","is_deleted":"0"},{"id":"17","username":"Vikas","prefix":"voda_fone","email":"vk.voda@gmail.com","comp_name":"vodafone","status":"1","is_deleted":"0"},{"id":"18","username":"gentlman","prefix":"usecode","email":"gent@gmail.com","comp_name":"getns","status":"1","is_deleted":"0"},{"id":"19","username":"Chandi","prefix":"chand","email":"chandi@gmail.com","comp_name":"K.Chand","status":"1","is_deleted":"0"},{"id":"20","username":"test2424525","prefix":"tes","email":"test2@gmail.com","comp_name":"test","status":"1","is_deleted":"0"},{"id":"25","username":"test242452","prefix":"tes","email":"test2@gmail.com","comp_name":"test","status":"1","is_deleted":"0"},
    {"id":"26","username":"bisu","prefix":"CB","email":"bisu.roy84@gmail.com","comp_name":"chandnibisu","status":"1","is_deleted":"0"},
    {"id":"27","username":"","prefix":"","email":"","comp_name":"","status":"1","is_deleted":"0"},
    {"id":"28","username":"shalini","prefix":"sha","email":"abc@gmail.com","comp_name":"abc","status":"1","is_deleted":"0"},
    {"id":"29","username":"abc","prefix":"a","email":"abc","comp_name":"abc","status":"1","is_deleted":"0"},
    {"id":"30","username":"simi","prefix":"sim","email":"simi","comp_name":"abc","status":"1","is_deleted":"0"}
];